image: crazyuploader/java_build_tools
tasks:
  - before: >
      [[ ! -z $GNUGPG  ]] &&
      DIR=`pwd` &&
      cd ~ &&
      rm -rf .gnupg &&
      echo $GNUGPG | base64 -d | tar --no-same-owner -xzvf - &&
      export GPG_TTY=$(tty) &&
      git config --global user.signingkey $GPG_KEY &&
      git config --global commit.gpgsign true
      cd $DIR
